version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB_FILE: /run/secrets/postgres_db
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
      POSTGRES_SHARED_PRELOAD_LIBRARIES: ""
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$(cat /run/secrets/postgres_user) -d $$(cat /run/secrets/postgres_db)"]
      interval: 10s
      timeout: 10s
      retries: 3
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 3
        window: 180s
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    networks:
      - app-network
    secrets:
      - postgres_db
      - postgres_user
      - postgres_password

  backend:
    image: ${REGISTRY:-localhost}/backend:latest
    command: >
      sh -c "
        export POSTGRES_DB=$$(cat /run/secrets/postgres_db) &&
        export POSTGRES_USER=$$(cat /run/secrets/postgres_user) &&
        export POSTGRES_PASSWORD=$$(cat /run/secrets/postgres_password) &&
        echo 'Esperando a que la base de datos esté lista...' &&
        sleep 10 &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000 --noreload
      "
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - app-network
    secrets:
      - postgres_db
      - postgres_user
      - postgres_password

  user-service:
    image: ${REGISTRY:-localhost}/user-service:latest
    command: >
      sh -c "
        export POSTGRES_DB=$$(cat /run/secrets/postgres_db) &&
        export POSTGRES_USER=$$(cat /run/secrets/postgres_user) &&
        export POSTGRES_PASSWORD=$$(cat /run/secrets/postgres_password) &&
        echo 'Esperando a que la base de datos esté lista...' &&
        sleep 12 &&
        npm start
      "
    ports:
      - "3003:3003"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - app-network
    secrets:
      - postgres_db
      - postgres_user
      - postgres_password

  posts-service:
    image: ${REGISTRY:-localhost}/posts-service:latest
    command: >
      sh -c "
        export POSTGRES_DB=$$(cat /run/secrets/postgres_db) &&
        export POSTGRES_USER=$$(cat /run/secrets/postgres_user) &&
        export POSTGRES_PASSWORD=$$(cat /run/secrets/postgres_password) &&
        echo 'Esperando a que la base de datos esté lista...' &&
        sleep 15 &&
        npm start
      "
    ports:
      - "3001:3001"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - app-network
    secrets:
      - postgres_db
      - postgres_user
      - postgres_password

  comments-service:
    image: ${REGISTRY:-localhost}/comments-service:latest
    command: >
      sh -c "
        export POSTGRES_DB=$$(cat /run/secrets/postgres_db) &&
        export POSTGRES_USER=$$(cat /run/secrets/postgres_user) &&
        export POSTGRES_PASSWORD=$$(cat /run/secrets/postgres_password) &&
        echo 'Esperando a que la base de datos esté lista...' &&
        sleep 20 &&
        python app.py
      "
    ports:
      - "3002:3002"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - app-network
    secrets:
      - postgres_db
      - postgres_user
      - postgres_password

  messages-service:
    image: ${REGISTRY:-localhost}/messages-service:latest
    command: >
      sh -c "
        export POSTGRES_DB=$$(cat /run/secrets/postgres_db) &&
        export POSTGRES_USER=$$(cat /run/secrets/postgres_user) &&
        export POSTGRES_PASSWORD=$$(cat /run/secrets/postgres_password) &&
        echo 'Esperando a que la base de datos esté lista...' &&
        sleep 18 &&
        npm start
      "
    ports:
      - "3004:3004"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - USER_SERVICE_URL=http://user-service:3003
    depends_on:
      - db
      - user-service
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - app-network
    secrets:
      - postgres_db
      - postgres_user
      - postgres_password

  frontend:
    image: ${REGISTRY:-localhost}/frontend:latest
    command: >
      sh -c "
        npm run build &&
        npm run preview -- --host 0.0.0.0
      "
    ports:
      - "4321:4321"
    depends_on:
      - backend
      - user-service
      - posts-service
      - comments-service
      - messages-service
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - app-network

secrets:
  postgres_db:
    external: true
  postgres_user:
    external: true
  postgres_password:
    external: true

volumes:
  postgres_data:

networks:
  app-network:
    driver: overlay
    attachable: true